name: assortment
version: 0.1.4+1
author: Christopher Best <bestchris@gmail.com>
description: Simple sortable DOM elements in Dart using HTML5 drag and drop
homepage: https://github.com/sirctseb/assortment
documentation: http://sirctseb.github.io/assortment
environment:
  sdk: '>=0.8.10+6 <3.0.0'
